# Generated by Django 5.2.8 on 2025-11-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название техники')),
                ('Weight', models.CharField(max_length=255, verbose_name='Грузоподьемность')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='evacuator/eva')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
                'ordering': ['name'],
            },
        ),
    ]
