# Generated by Django 5.2.8 on 2025-11-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuator', '0002_eva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Цена'),
        ),
    ]
