# Generated by Django 5.2.8 on 2025-11-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuator', '0003_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='evacuator/contact'),
        ),
    ]
