# Generated by Django 5.2.8 on 2025-11-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuator', '0004_contact_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, help_text='Если вы хотите получить ответ, оставьте свой номер телефона. Если желаете оставить отзыв, можете не оставлять номер', null=True, verbose_name='Сообщение'),
        ),
    ]
