# Generated by Django 5.2.8 on 2025-11-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuator', '0005_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['question'],
            },
        ),
    ]
