# Generated by Django 5.2.8 on 2025-11-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuator', '0006_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='static',
            name='email',
        ),
        migrations.RemoveField(
            model_name='static',
            name='map',
        ),
        migrations.AddField(
            model_name='static',
            name='cooperation',
            field=models.TextField(blank=True, null=True, verbose_name='Сотрудничество'),
        ),
    ]
